---
'on':
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            shell: bash -e
          - runs-on: macos-latest
            shell: bash -e
          - runs-on: windows-latest
            shell: msys2
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: ${{matrix.shell}} {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
      - name: Install dependencies
        if: runner.os == 'Windows'
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-nodejs mingw-w64-x86_64-gcc \
            make
      - uses: actions/setup-node@v4
        if: runner.os != 'Windows'
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - name: Build
        run: |
          npm install
          npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            prebuilds/*

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: prebuilds
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - name: Build
        run: |
          chmod +x prebuilds/*/bin/*
          npm install
          npm pack
      - uses: softprops/action-gh-release@v2
        with:
          files: '*.tgz'
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NODE_ENV: production
        run: |
          npm publish
